name: autofix.ci
on:
  workflow_call:
  pull_request:
  push:
    branches: [ "main" ]
permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Use uv to ensure we have the same ruff version in CI and locally.
      - uses: astral-sh/setup-uv@77c28f02b3322332d4a4446b3177f426da8bf086
        with:
          version: "0.4.20"
      # Fix lint errors
      - run: uv run ruff check --fix-only .
      # Format code
      - run: uv run ruff format .

      - uses: autofix-ci/action@dd55f44df8f7cdb7a6bf74c78677eb8acd40cd0a
